<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>20_異常穿透</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
  <div class="container"></div>
  <script>
    let p = new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve('ok');
        // reject('no');
      }, 1000);
    });

    p.then(value => {
      console.log(111);
      throw '失敗了';
    }).then(value => {
      console.log(222);
    }).then(value => {
      console.log(333);
    }).catch(reason => {
      console.warn(reason);
    });

    // 只要在最後加上 catch 就可以捕獲所有的錯誤(這邊是第一個接收的 reject)

  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>